import { Platform } from '@/enums/Platform'
import { MainConfig } from '@/interfaces/MainConfig'

export const mainConfig: MainConfig = {
  title: 'ModuleArt',
  description: 'Best apps with love',
  projects: [
    {
      title: 'PlainColor',
      shortDescription: 'Lightweight stylish cross-platform color picker app',
      longDescription: '',
      href: '/plain-color',
      appIcon: '/assets/images/projects/plain-color/icon.png',
      images: ['/assets/images/projects/plain-color/1.webp'],
      githubPath: 'ModuleArt/plain-color',
      donateUrl: 'https://opencollective.com/moduleart/projects/plaincolor',
      platform: Platform.mac,
      os: 'macOS 10.15+',
      authorName: 'Eugene Volynko',
      authorUrl: 'https://github.com/Beelink',
    },
    {
      title: 'Quick Picture Viewer',
      shortDescription: 'Lightweight, versatile desktop image viewer for Windows',
      longDescription:
        'Small and fast but still have a bunch of features. 20+ formats supported. Works great with GIF, SVG, PNG, WEBP, ICO, BMP, DDS, TGA, CR2 etc.',
      href: '/quick-picture-viewer',
      appIcon: '/assets/images/projects/quick-picture-viewer/icon.png',
      images: ['/assets/images/projects/quick-picture-viewer/1.png', '/assets/images/projects/quick-picture-viewer/2.png'],
      githubPath: 'ModuleArt/quick-picture-viewer',
      donateUrl: 'https://opencollective.com/moduleart/projects/quick-picture-viewer',
      platform: Platform.win,
      os: 'Windows 7+',
      authorName: 'Eugene Volynko',
      authorUrl: 'https://github.com/Beelink',
    },
    {
      title: 'SzContext',
      shortDescription: 'Open files or folders using your favorite app from Finder® context menu',
      longDescription: 'Provides your favorite apps at your hands. Open files or folders using your favorite app from Finder® context menu',
      href: '/sz-context',
      appIcon: '/assets/images/projects/sz-context/icon.png',
      images: [
        '/assets/images/projects/sz-context/1.png',
        '/assets/images/projects/sz-context/2.png',
        '/assets/images/projects/sz-context/3.png',
        '/assets/images/projects/sz-context/4.png',
      ],
      githubPath: 'RoadToDream/SzContext',
      platform: Platform.mac,
      os: 'macOS 10.15+',
      authorName: 'Duan Jiawei',
      authorUrl: 'https://github.com/RoadToDream',
    },
    {
      title: 'Quick Color Picker',
      shortDescription: 'Lightweight desktop color picker and color editor utility for Windows',
      longDescription: '',
      href: '/quick-color-picker',
      appIcon: '/assets/images/projects/quick-color-picker/icon.png',
      images: ['/assets/images/projects/quick-color-picker/1.png', '/assets/images/projects/quick-color-picker/2.png'],
      githubPath: 'ModuleArt/quick-color-picker',
      platform: Platform.win,
      os: 'Windows 7+',
      authorName: 'Eugene Volynko',
      authorUrl: 'https://github.com/Beelink',
    },
  ],
}
